//头部导航
document.writeln("<link href=\"../include/Css/head.css\" type=\"text/css\" rel=\"stylesheet\" >");
document.writeln("<div id=\"header\">");
document.writeln("  <nav>");
document.writeln("       <div class=\"kbj-header\">");
document.writeln("        <div class=\"kbj-header-wrap\">");
document.writeln("              <div class=\"kbj-header-logo\">");
document.writeln("                 <h1><a href=\"\/\">南京康贝佳口腔医院</a></h1></div>");
document.writeln("             <div class=\"nav_menu\">");
document.writeln("            <ul class=\"kbj-header-link\">");
document.writeln("              <li class=\"kbj-header-link-product\"><a href=\"/\" class=\"a\">首页</a></li>");
document.writeln("            <li id=\"kbj-header-link-product\" class=\"kbj-header-link-product\"><a href=\"/yypp/\" class=\"a\">品牌</a></li>");
document.writeln("       <li id=\"kbj-header-link-product1\" class=\"kbj-header-link-product\"><a href=\"/zlxm/\" class=\"a\">项目</a></li>");
document.writeln("       <li><a href=\"/yydt/\" class=\"a\">动态</a>");
document.writeln("       <div class=\"nav_hover a1\">");
document.writeln("       <dl><dt>最新动态</dt>");
document.writeln("       <dd>尽览医院最新动态</dd>");
document.writeln("    </dl>");
document.writeln("  </div>");
document.writeln("  </li>");
document.writeln(" <li><a href=\"/ystd/\" class=\"a\">团队</a>");
document.writeln("  <div class=\"nav_hover a2\">");
document.writeln("    <dl><dt>医疗团队</dt>");
document.writeln("      <dd>生动感知医院团队风采</dd>");
document.writeln("   </dl>");
document.writeln("  </div>");
document.writeln("  </li>");
document.writeln("  <li><a  href=\"/lylx/\" class=\"a\">路线</a>");

document.writeln("</li>");
document.writeln("  <li><a href=\"/zzgh/\" class=\"a\">挂号</a>");
document.writeln(" <div class=\"nav_hover a4\">");
document.writeln("  <dl><dt>自助挂号</dt>");
document.writeln("     <dd>即时在线伺服，沟通如此用心</dd>");
document.writeln("  </dl>");
document.writeln("   </div>");
document.writeln(" </li>");
document.writeln(" </ul>");
document.writeln(" </div>");
document.writeln(" </div>");
document.writeln("  </div>");


document.writeln("  <div id=\"kbj-header-sub\" class=\"kbj-header-sub\">");
document.writeln("    <div class=\"xiangmunr_div\">");
document.writeln("      <ul class=\"xiangmunr\">");
document.writeln("     <li id=\"dhsj1\" onmouseover=\"box('dhsj','dhsjBoxs',1,9);\" class=\"bbp\"><a href=\"/yypp/#1\"><i class=\"ppjs1\"></i><p>品牌介绍</p></a></li>");
document.writeln("     <li id=\"dhsj2\" onmouseover=\"box('dhsj','dhsjBoxs',2,9);\"><a href=\"/yypp/#2\"><i class=\"ppjs2\"></i><p>大事记</p></a></li>");
document.writeln("    <li id=\"dhsj3\" onmouseover=\"box('dhsj','dhsjBoxs',3,9);\"><a href=\"/yypp/#3\"><i class=\"ppjs3\"></i><p>爱心公益</p></a></li>");
document.writeln("   <li id=\"dhsj4\" onmouseover=\"box('dhsj','dhsjBoxs',4,9);\"><a href=\"/yypp/#4\"><i class=\"ppjs4\"></i><p>品牌理念</p></a></li>");
document.writeln("   <li id=\"dhsj5\" onmouseover=\"box('dhsj','dhsjBoxs',5,9);\"><a href=\"/yypp/#5\"><i class=\"ppjs5\"></i><p>服务理念</p></a></li>");
document.writeln("    <li id=\"dhsj6\" onmouseover=\"box('dhsj','dhsjBoxs',6,9);\"><a href=\"/yypp/#6\"><i class=\"ppjs6\"></i><p>品牌荣誉</p></a></li>");
document.writeln("   <li id=\"dhsj7\" onmouseover=\"box('dhsj','dhsjBoxs',7,9);\"><a href=\"/yypp/#7\"><i class=\"ppjs7\"></i><p>品牌特色</p></a></li>");
document.writeln("   <li id=\"dhsj8\" onmouseover=\"box('dhsj','dhsjBoxs',8,9);\" style=\"margin-right:0;\"><a href=\"/yypp/#8\"><i class=\"ppjs8\"></i><p>安全保障</p></a></li>");

document.writeln("  <div id=\"dhsjBoxs1\"></div>");
document.writeln("  <div id=\"dhsjBoxs2\" class=\"disnone\"></div>");
document.writeln("   <div id=\"dhsjBoxs3\" class=\"disnone\"></div>");
document.writeln("  <div id=\"dhsjBoxs4\" class=\"disnone\"></div>");
document.writeln("   <div id=\"dhsjBoxs5\" class=\"disnone\"></div>");
document.writeln("  <div id=\"dhsjBoxs6\" class=\"disnone\"></div>");
document.writeln("  <div id=\"dhsjBoxs7\" class=\"disnone\"></div>");
document.writeln("  </ul>");
document.writeln(" </div>");
document.writeln(" </div>");



document.writeln("  <div id=\"kbj-header-sub1\" class=\"kbj-header-sub\">");
document.writeln("    <div class=\"header_nav_km\">");
document.writeln("     <ul>");
document.writeln("      <li>");
document.writeln("     <a href=\"/zlxm/#1\"><img src=\"../include/Picture/km_nav_01.jpg\">");
document.writeln("       <p>牙齿种植</p>");
document.writeln("     </a>");
document.writeln("    </li>");
document.writeln("     <li>");
document.writeln("     <a href=\"/zlxm/#2\"><img src=\"../include/Picture/km_nav_02.jpg\">");
document.writeln("      <p>牙齿矫正</p>");
document.writeln("    </a>");
document.writeln("   </li>");
document.writeln("   <li>");
document.writeln("    <a href=\"/zlxm/#3\"><img src=\"../include/Picture/km_nav_03.jpg\">");
document.writeln("      <p>牙齿修复</p>");
document.writeln("  </a>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("    <a href=\"/zlxm/#4\"><img src=\"../include/Picture/km_nav_04.jpg\">");
document.writeln("      <p>牙齿美白</p>");
document.writeln("    </a>");
document.writeln("    </li>");
document.writeln("    <li>");
document.writeln("     <a href=\"/zlxm/#5\"><img src=\"../include/Picture/km_nav_05.jpg\">");
document.writeln("       <p>牙齿治疗</p>");
document.writeln("    </a>");
document.writeln("    </li>");
document.writeln(" <li>");
document.writeln(" <a href=\"/zlxm/#6\"><img src=\"../include/Picture/km_nav_06.jpg\">");
document.writeln("   <p>儿童齿科</p>");
document.writeln("   </a>");
document.writeln("   </li>");
document.writeln("  </ul>");
document.writeln("  </div>");
document.writeln("  </div>");
document.writeln("  </nav>");
document.writeln("  </div>");